version: '3.8'

services:
  backend:
    build: ./backend  # Points to the backend folder
    container_name: portal-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./frontend # Points to the frontend folder
    container_name: portal-frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge